name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.7', '3.0', '3.1', 'head']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}

    env:
      POLYPHONY_USE_LIBEV: "1"

    steps:
    - name: Setup machine
      uses: actions/checkout@v1
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true # 'bundle install' and cache
        cache-version: 2
    - name: Kernel version
      run: uname -a
    - name: Compile C-extension
      run: bundle exec rake compile
    - name: Run tests
      run:  bundle exec rake test
